### ISSUE TITLE
Stops on 404 405

### ISSUE THREAD

**Issue by yene** [tj/staticgen#12]
Crawler stops on 404 or 405

**Comment by tj** [comment]
I forgot to document this option: https://github.com/tj/staticgen/blob/master/config.go#L28 that should do the trick, at least for 404

**Comment by skatkov** [comment]
Got stuck on 404 too.

used this config, but still staticgen doesn't progress beyong 404 error.

```
{
  "url": "https://www.tssltd.ru",
  "concurrency": 1,
  "dir": "tss-dist",
  "allow_404": true
}
```

What am I doing wrong?

**Comment by tj** [comment]
Hmm I'll try to check it out soon, config looks fine to me

**Comment by skatkov** [comment]
@tj did you had time to give it a look?  Maybe some pointers where problem could be?

**Comment by tj** [comment]
not yet sorry! A quick grep doesn't show Allow404 anywhere though, looks like I maybe added the config but didn't implement it yet
