### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by steren** [tj/staticgen#13]
I'm on ChromeOS, I follow the install instructions:

```
$ curl -sf https://gobinaries.com/tj/staticgen/cmd/staticgen | sh

\x1b[38;5;61m  ==>\x1b[0;00m Downloading github.com/tj/staticgen/cmd/staticgen@master
\x1b[38;5;61m  ==>\x1b[0;00m Resolved version master to v1.0.1
\x1b[38;5;61m  ==>\x1b[0;00m Downloading binary for linux amd64
\x1b[38;5;61m  ==>\x1b[0;00m Installing staticgen to /usr/local/bin
install: cannot change permissions of ‘/usr/local/bin’: Operation not permitted
```

Alternatively, could there be a way to execute `staticgen` without installing it? the `curl | sh` command could execute the binary instead of installing it.

**Comment by steren** [comment]
The same happens on GitPod or Google Cloud Shell: 

```
$ curl -sf https://gobinaries.com/tj/staticgen/cmd/staticgen | sh

\x1b[38;5;61m  ==>\x1b[0;00m Downloading github.com/tj/staticgen/cmd/staticgen@master
\x1b[38;5;61m  ==>\x1b[0;00m Resolved version master to v1.0.1
\x1b[38;5;61m  ==>\x1b[0;00m Downloading binary for linux amd64
\x1b[38;5;61m  ==>\x1b[0;00m Installing staticgen to /usr/local/bin
install: cannot create regular file '/usr/local/bin/staticgen': Permission denied
```

**Comment by tj** [comment]
Ahhh try `curl -sf https://gobinaries.com/tj/staticgen/cmd/staticgen | sudo sh`, I was kind of debating recommending sudo by default but it should at least be documented, or `curl -sf https://gobinaries.com/tj/staticgen/cmd/staticgen | PREFIX=~/bin sh` for people who aren't into using /usr/local/bin

**Comment by steren** [comment]
Thanks, it works.

I tried with `sudo` before `curl`, but not before `sh`

Yes, I would recommend mentioning it in the README, as I expect most users to have to do this.

**Comment by tj** [comment]
If you run `curl -sf https://gobinaries.com/tj/staticgen/cmd/staticgen | sh` it should be ok now, snuck a `sudo install ...` in there

**Comment by steren** [comment]
Oh that's perfect, thanks
